//
//  Workspace.swift
//  _TuistAppManifests
//
//  Created by 김영훈 on 9/15/26.
//

import ProjectDescription
import ProjectDescriptionHelpers

let workspace = Workspace(
    name: AppConstants.appName,
    projects: [
        "App",
        "Modules/**",
    ],
    // 자동 생성 스킴은 테스트 타깃까지 빌드 액션에 넣어 Release 빌드가 깨진다. `Scheme.workspace()` 참고.
    schemes: [.workspace()],
    additionalFiles: [
        "Configurations/**",
        "README.md",
    ],
    generationOptions: .options(autogeneratedWorkspaceSchemes: .disabled)
)
